[package]
name = "UniCall"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
unicall = "0x0"
wormhole = "0x31358d198147da50db32eda2562951d53973a0c0ad5ed738e9b17d88b213d790"