/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { RELAYER_NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const ROLLUP_TRANSACTION_DISCRIMINATOR = 15;

export function getRollupTransactionDiscriminatorBytes() {
  return getU8Encoder().encode(ROLLUP_TRANSACTION_DISCRIMINATOR);
}

export type RollupTransactionInstruction<
  TProgram extends string = typeof RELAYER_NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountBallotBox extends string | IAccountMeta<string> = string,
  TAccountHubConfig extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountRelayerHubProgram extends string | IAccountMeta<string> = string,
  TAccountRestakingProgram extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTransaction extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountBallotBox extends string
        ? ReadonlyAccount<TAccountBallotBox>
        : TAccountBallotBox,
      TAccountHubConfig extends string
        ? ReadonlyAccount<TAccountHubConfig>
        : TAccountHubConfig,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountRelayerHubProgram extends string
        ? ReadonlyAccount<TAccountRelayerHubProgram>
        : TAccountRelayerHubProgram,
      TAccountRestakingProgram extends string
        ? ReadonlyAccount<TAccountRestakingProgram>
        : TAccountRestakingProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTransaction extends string
        ? WritableAccount<TAccountTransaction>
        : TAccountTransaction,
      ...TRemainingAccounts,
    ]
  >;

export type RollupTransactionInstructionData = {
  discriminator: number;
  epoch: bigint;
};

export type RollupTransactionInstructionDataArgs = { epoch: number | bigint };

export function getRollupTransactionInstructionDataEncoder(): Encoder<RollupTransactionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ROLLUP_TRANSACTION_DISCRIMINATOR })
  );
}

export function getRollupTransactionInstructionDataDecoder(): Decoder<RollupTransactionInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getRollupTransactionInstructionDataCodec(): Codec<
  RollupTransactionInstructionDataArgs,
  RollupTransactionInstructionData
> {
  return combineCodec(
    getRollupTransactionInstructionDataEncoder(),
    getRollupTransactionInstructionDataDecoder()
  );
}

export type RollupTransactionInput<
  TAccountConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountBallotBox extends string = string,
  TAccountHubConfig extends string = string,
  TAccountPool extends string = string,
  TAccountRelayerHubProgram extends string = string,
  TAccountRestakingProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTransaction extends string = string,
> = {
  config: Address<TAccountConfig>;
  ncn: Address<TAccountNcn>;
  ballotBox: Address<TAccountBallotBox>;
  hubConfig: Address<TAccountHubConfig>;
  pool: Address<TAccountPool>;
  relayerHubProgram: Address<TAccountRelayerHubProgram>;
  restakingProgram: Address<TAccountRestakingProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  transaction: Address<TAccountTransaction>;
  epoch: RollupTransactionInstructionDataArgs['epoch'];
};

export function getRollupTransactionInstruction<
  TAccountConfig extends string,
  TAccountNcn extends string,
  TAccountBallotBox extends string,
  TAccountHubConfig extends string,
  TAccountPool extends string,
  TAccountRelayerHubProgram extends string,
  TAccountRestakingProgram extends string,
  TAccountSystemProgram extends string,
  TAccountTransaction extends string,
  TProgramAddress extends Address = typeof RELAYER_NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: RollupTransactionInput<
    TAccountConfig,
    TAccountNcn,
    TAccountBallotBox,
    TAccountHubConfig,
    TAccountPool,
    TAccountRelayerHubProgram,
    TAccountRestakingProgram,
    TAccountSystemProgram,
    TAccountTransaction
  >,
  config?: { programAddress?: TProgramAddress }
): RollupTransactionInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountNcn,
  TAccountBallotBox,
  TAccountHubConfig,
  TAccountPool,
  TAccountRelayerHubProgram,
  TAccountRestakingProgram,
  TAccountSystemProgram,
  TAccountTransaction
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? RELAYER_NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    ncn: { value: input.ncn ?? null, isWritable: false },
    ballotBox: { value: input.ballotBox ?? null, isWritable: false },
    hubConfig: { value: input.hubConfig ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    relayerHubProgram: {
      value: input.relayerHubProgram ?? null,
      isWritable: false,
    },
    restakingProgram: {
      value: input.restakingProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.ballotBox),
      getAccountMeta(accounts.hubConfig),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.relayerHubProgram),
      getAccountMeta(accounts.restakingProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.transaction),
    ],
    programAddress,
    data: getRollupTransactionInstructionDataEncoder().encode(
      args as RollupTransactionInstructionDataArgs
    ),
  } as RollupTransactionInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountNcn,
    TAccountBallotBox,
    TAccountHubConfig,
    TAccountPool,
    TAccountRelayerHubProgram,
    TAccountRestakingProgram,
    TAccountSystemProgram,
    TAccountTransaction
  >;

  return instruction;
}

export type ParsedRollupTransactionInstruction<
  TProgram extends string = typeof RELAYER_NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    ncn: TAccountMetas[1];
    ballotBox: TAccountMetas[2];
    hubConfig: TAccountMetas[3];
    pool: TAccountMetas[4];
    relayerHubProgram: TAccountMetas[5];
    restakingProgram: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
    transaction: TAccountMetas[8];
  };
  data: RollupTransactionInstructionData;
};

export function parseRollupTransactionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRollupTransactionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      ncn: getNextAccount(),
      ballotBox: getNextAccount(),
      hubConfig: getNextAccount(),
      pool: getNextAccount(),
      relayerHubProgram: getNextAccount(),
      restakingProgram: getNextAccount(),
      systemProgram: getNextAccount(),
      transaction: getNextAccount(),
    },
    data: getRollupTransactionInstructionDataDecoder().decode(instruction.data),
  };
}
