[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/relayer_solana",
    "programs/proxy",
    "programs/test",
    "programs/stake",
    "programs/nft_verification"
#    "programs/token_bridge_relayer",
]
[programs.localnet]
relayer_solana = "5tFEXwUwpAzMXBWUSjQNWVfEh7gKbTc5hQMqBwi8jQ7k"
proxy = "E8MhaNDD1nPQzCRCu1KPjuofFcbkjzY6tzvWwLjQxLw5"
test = "DViLwexyLUuKRRXWCQgFYqzoVLWktEbvUVhzKNZ7qTSF"
stake = "29fp9FCyJjrT91TDyx5VPGTMinXqrRAbAbd634U7ZiXw"
nft_verification = "3b5KJUApvzf8Pz1DMrkLNpaWkUBvmJK8WQQcWiRSvZb3"
#token_bridge_relayer = "EYcqMLNRMUkHvDMg2Jpng8R5HMeJgt8uX7q372omPVsD"
[programs.devnet]
relayer_solana = "5tFEXwUwpAzMXBWUSjQNWVfEh7gKbTc5hQMqBwi8jQ7k"
proxy = "E8MhaNDD1nPQzCRCu1KPjuofFcbkjzY6tzvWwLjQxLw5"
test = "DViLwexyLUuKRRXWCQgFYqzoVLWktEbvUVhzKNZ7qTSF"
stake = "29fp9FCyJjrT91TDyx5VPGTMinXqrRAbAbd634U7ZiXw"
nft_verification = "3b5KJUApvzf8Pz1DMrkLNpaWkUBvmJK8WQQcWiRSvZb3"
#token_bridge_relayer = "EYcqMLNRMUkHvDMg2Jpng8R5HMeJgt8uX7q372omPVsD"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./target/deploy/user.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
