[toolchain]

[workspace]
members = [
    "programs/*",
]
[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_verification = "3b5KJUApvzf8Pz1DMrkLNpaWkUBvmJK8WQQcWiRSvZb3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
