[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/hackathon",
    "programs/proxy",
    "programs/test",
]
[programs.localnet]
hackathon = "CLErExd7gNADvu5rDFmkFD1uAt7zksJ3TDfXsJqJ4QTs"
proxy = "E8MhaNDD1nPQzCRCu1KPjuofFcbkjzY6tzvWwLjQxLw5"
test = "DViLwexyLUuKRRXWCQgFYqzoVLWktEbvUVhzKNZ7qTSF"
[programs.devnet]
hackathon = "CLErExd7gNADvu5rDFmkFD1uAt7zksJ3TDfXsJqJ4QTs"
proxy = "E8MhaNDD1nPQzCRCu1KPjuofFcbkjzY6tzvWwLjQxLw5"
test = "DViLwexyLUuKRRXWCQgFYqzoVLWktEbvUVhzKNZ7qTSF"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
