[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/hackathon",
    "programs/proxy",
    "programs/test",
    "programs/stake",
    "programs/token_bridge_relayer",
]
[programs.localnet]
hackathon = "CLErExd7gNADvu5rDFmkFD1uAt7zksJ3TDfXsJqJ4QTs"
proxy = "E8MhaNDD1nPQzCRCu1KPjuofFcbkjzY6tzvWwLjQxLw5"
test = "DViLwexyLUuKRRXWCQgFYqzoVLWktEbvUVhzKNZ7qTSF"
stake = "29fp9FCyJjrT91TDyx5VPGTMinXqrRAbAbd634U7ZiXw"
token_bridge_relayer = "EYcqMLNRMUkHvDMg2Jpng8R5HMeJgt8uX7q372omPVsD"
[programs.devnet]
hackathon = "CLErExd7gNADvu5rDFmkFD1uAt7zksJ3TDfXsJqJ4QTs"
proxy = "E8MhaNDD1nPQzCRCu1KPjuofFcbkjzY6tzvWwLjQxLw5"
test = "DViLwexyLUuKRRXWCQgFYqzoVLWktEbvUVhzKNZ7qTSF"
stake = "29fp9FCyJjrT91TDyx5VPGTMinXqrRAbAbd634U7ZiXw"
token_bridge_relayer = "EYcqMLNRMUkHvDMg2Jpng8R5HMeJgt8uX7q372omPVsD"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
