[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/relayer-hub",
    "programs/relayer-ncn",
]
[programs.mainnet]
relayer_hub = "48Xgerygjftsx9brotJQbkDZtLov9Gyuj4G3Y7eMirJL"
relayer_ncn = "J2rxY1z3Wgt4VYrN4EVh6FGnEZHnEyHqQcwvd2kfKnxh"

[programs.localnet]
relayer_hub = "48Xgerygjftsx9brotJQbkDZtLov9Gyuj4G3Y7eMirJL"
relayer_ncn = "J2rxY1z3Wgt4VYrN4EVh6FGnEZHnEyHqQcwvd2kfKnxh"

[programs.devnet]
relayer_hub = "48Xgerygjftsx9brotJQbkDZtLov9Gyuj4G3Y7eMirJL"
relayer_ncn = "J2rxY1z3Wgt4VYrN4EVh6FGnEZHnEyHqQcwvd2kfKnxh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
