[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/relayer-hub",
]
[programs.mainnet]
relayer_hub = "25dmj8Y96VsSGMz4acYpfXD66vFSDNn8wB5wz1gmNZsH"

[programs.localnet]
relayer_hub = "25dmj8Y96VsSGMz4acYpfXD66vFSDNn8wB5wz1gmNZsH"

[programs.devnet]
relayer_hub = "25dmj8Y96VsSGMz4acYpfXD66vFSDNn8wB5wz1gmNZsH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
