[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/relayer-hub",
]
[programs.mainnet]
relayer_hub = "39djqgS6KR6SWb3T39bTj8QMX3iuMMLP41PVjk89ieJh"

[programs.localnet]
relayer_hub = "39djqgS6KR6SWb3T39bTj8QMX3iuMMLP41PVjk89ieJh"

[programs.devnet]
relayer_hub = "39djqgS6KR6SWb3T39bTj8QMX3iuMMLP41PVjk89ieJh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./target/deploy/owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
